parameters:
#    project_admin.example.class: AppBundle\Example

services:
#    project_admin.example:
#        class: %project_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

